"""Compatibility exports for agentsassemble.room.attachments."""

from agentsassemble.room.attachments import (
    ATTACHMENT_ID_PATTERN,
    AttachmentError,
    FileAttachmentStore,
    INLINE_SAFE_IMAGE_TYPES,
    MAX_ATTACHMENTS_PER_EVENT,
    MAX_ATTACHMENT_BYTES,
    attachment_content_disposition,
    attachment_root,
    decode_attachment_data,
    normalize_attachment_id,
    normalize_attachment_references,
    normalize_content_type,
    normalize_size,
    public_attachment_metadata,
    read_attachment_file,
    read_attachment_metadata,
    sanitize_attachment_filename,
    store_uploaded_attachment,
)

__all__ = [
    'ATTACHMENT_ID_PATTERN',
    'AttachmentError',
    'FileAttachmentStore',
    'INLINE_SAFE_IMAGE_TYPES',
    'MAX_ATTACHMENTS_PER_EVENT',
    'MAX_ATTACHMENT_BYTES',
    'attachment_content_disposition',
    'attachment_root',
    'decode_attachment_data',
    'normalize_attachment_id',
    'normalize_attachment_references',
    'normalize_content_type',
    'normalize_size',
    'public_attachment_metadata',
    'read_attachment_file',
    'read_attachment_metadata',
    'sanitize_attachment_filename',
    'store_uploaded_attachment',
]
