"""Compatibility exports for the resident Cursor CLI adapter."""

from agentsassemble.providers.cursor_resident import (
    CURSOR_AUTH_REQUIRED,
    CURSOR_EMPTY_TEXT,
    CURSOR_GENERIC_RESIDENT_UNSUPPORTED_MESSAGE,
    CURSOR_INVALID_CHAT_ID,
    CURSOR_LOGIN_REQUIRED_MESSAGE,
    CURSOR_SUBPROCESS_NONZERO,
    CURSOR_SUBPROCESS_TIMEOUT,
    CURSOR_TERMINAL_SESSION_SUPERSEDED_MESSAGE,
    CursorResidentCommandRunner,
    CursorResidentRuntimeError,
    CursorResidentValueError,
    clean_cursor_chat_id,
    cursor_auth_check,
    cursor_command_check,
    cursor_error_category,
    cursor_generic_resident_guard_check,
    cursor_generic_resident_guard_error,
    cursor_login_required_message,
    cursor_provider_connection_check,
    cursor_terminal_session_superseded_check,
    cursor_terminal_session_superseded_error,
    default_cursor_resident_command,
)


__all__ = [
    "CURSOR_AUTH_REQUIRED",
    "CURSOR_EMPTY_TEXT",
    "CURSOR_GENERIC_RESIDENT_UNSUPPORTED_MESSAGE",
    "CURSOR_INVALID_CHAT_ID",
    "CURSOR_LOGIN_REQUIRED_MESSAGE",
    "CURSOR_SUBPROCESS_NONZERO",
    "CURSOR_SUBPROCESS_TIMEOUT",
    "CURSOR_TERMINAL_SESSION_SUPERSEDED_MESSAGE",
    "CursorResidentCommandRunner",
    "CursorResidentRuntimeError",
    "CursorResidentValueError",
    "clean_cursor_chat_id",
    "cursor_auth_check",
    "cursor_command_check",
    "cursor_error_category",
    "cursor_generic_resident_guard_check",
    "cursor_generic_resident_guard_error",
    "cursor_login_required_message",
    "cursor_provider_connection_check",
    "cursor_terminal_session_superseded_check",
    "cursor_terminal_session_superseded_error",
    "default_cursor_resident_command",
]
