"""Compatibility exports for the application-scoped room user facade."""

from agentsassemble.application.room_users import (
    IDENTITY_DB_FILENAME,
    LOCAL_OPERATOR_PARTICIPANT_ID,
    PARTICIPANT_TYPES,
    IdentityBackend,
    configure_room_users_backend,
    configure_room_users_store,
    default_room_users_store_path,
    device_auth_key,
    get_room,
    grant_operator_to_device,
    list_rooms,
    normalize_participant_type,
    operator_user_id,
    participant_is_operator,
    release_room_users_backend,
    reset_state,
    resolve_device_user,
    set_room_archived,
    touch_room,
    upsert_room,
    user_for_device_token,
    user_for_participant,
)


__all__ = [
    "IDENTITY_DB_FILENAME",
    "LOCAL_OPERATOR_PARTICIPANT_ID",
    "PARTICIPANT_TYPES",
    "IdentityBackend",
    "configure_room_users_backend",
    "configure_room_users_store",
    "default_room_users_store_path",
    "device_auth_key",
    "get_room",
    "grant_operator_to_device",
    "list_rooms",
    "normalize_participant_type",
    "operator_user_id",
    "participant_is_operator",
    "release_room_users_backend",
    "reset_state",
    "resolve_device_user",
    "set_room_archived",
    "touch_room",
    "upsert_room",
    "user_for_device_token",
    "user_for_participant",
]
