"""Compatibility exports for the optional local social profile."""
from agentsassemble.features.social.profile import (
    AVATAR_LABEL_LIMIT,
    CUSTOM_STATUS_LIMIT,
    DEFAULT_PROFILE,
    IMAGE_URL_LIMIT,
    PROFILE_TEXT_LIMIT,
    VALID_BANNER_PRESETS,
    VALID_STATUSES,
    clean_accent_color,
    clean_avatar_image_url,
    clean_avatar_label,
    clean_banner_preset,
    clean_profile_text,
    clean_status,
    public_user_profile,
    read_user_profile,
    update_user_profile,
)

__all__ = [
    "AVATAR_LABEL_LIMIT",
    "CUSTOM_STATUS_LIMIT",
    "DEFAULT_PROFILE",
    "IMAGE_URL_LIMIT",
    "PROFILE_TEXT_LIMIT",
    "VALID_BANNER_PRESETS",
    "VALID_STATUSES",
    "clean_accent_color",
    "clean_avatar_image_url",
    "clean_avatar_label",
    "clean_banner_preset",
    "clean_profile_text",
    "clean_status",
    "public_user_profile",
    "read_user_profile",
    "update_user_profile",
]
