import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class DocsArchitectureTests(unittest.TestCase):
    def test_product_operating_model_records_agentsassemble_specific_memory(self):
        doc = (ROOT / "docs" / "product" / "OPERATING_MODEL.md").read_text(encoding="utf-8")
        agents = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
        roadmap = (ROOT / "docs" / "roadmap.md").read_text(encoding="utf-8")

        self.assertIn("AgentsAssemble Operating Model", doc)
        self.assertIn("discovery is not execution", doc)
        self.assertIn("meeting room startup must not launch real provider CLIs", doc)
        self.assertIn("host-approved session", doc)
        self.assertIn("agent-private context", doc)
        self.assertIn("shared meeting memory", doc)
        self.assertIn("Work Mode", doc)
        self.assertIn("Play Mode", doc)
        self.assertIn("official record", doc)
        self.assertIn("rolling summary", doc)
        self.assertIn("shared_memory/rolling-summary.md", doc)
        self.assertIn("shared_memory/open-questions.md", doc)
        self.assertIn("shared_memory/action-items.md", doc)
        self.assertIn("shared_memory/index.json", doc)
        self.assertIn("compact shared memory into resident prompts", doc)
        self.assertIn("source event, cursor metadata, identity, and explicit shared meeting memory", doc)
        self.assertIn("frontend polish is deferred", doc)
        self.assertIn("Viewooa", doc)
        self.assertIn("Do not copy Viewooa files", doc)
        self.assertIn("docs/product/OPERATING_MODEL.md", agents)
        self.assertIn("docs/product/OPERATING_MODEL.md", roadmap)

    def test_operating_model_records_room_first_agent_owned_context(self):
        operating_model = (ROOT / "docs" / "product" / "OPERATING_MODEL.md").read_text(encoding="utf-8")
        live_agent_ops = (ROOT / "docs" / "live-agent-ops.md").read_text(encoding="utf-8")
        combined = "\n".join([operating_model, live_agent_ops])

        self.assertIn("Room-first / Agent-owned Context", combined)
        self.assertIn("The room is a room, not a hidden moderator", combined)
        self.assertIn("Agents decide what extra context to read", combined)
        self.assertIn("Agent-owned entry is the primary resident direction", combined)
        self.assertIn("join briefs are entry packets", combined)
        self.assertIn("MCP participant or self-service loops", combined)
        self.assertIn("Play Mode `flow` remains a demo/social helper", combined)
        self.assertIn("cursor/diff", combined)
        self.assertIn("last_observed_event_id", combined)
        self.assertIn("last_observed_live_event_id", combined)
        self.assertIn("moderator does not sit between every room event and every agent reply", combined)

    def test_live_session_room_model_documents_shared_room_semantics(self):
        doc = (ROOT / "docs" / "live-session-room-model.md").read_text(encoding="utf-8")

        self.assertIn("shared room event stream", doc)
        self.assertIn("Agents do not receive isolated interview prompts", doc)
        self.assertIn("human", doc)
        self.assertIn("local_cli delegate", doc)
        self.assertIn("live_session", doc)
        self.assertIn("partial prefix/suffix matches do not count as a call", doc)
        self.assertIn("Codex app", doc)
        self.assertIn("CLI", doc)
        self.assertIn("memory capsule", doc)
        self.assertIn("memory-capsule gate", doc)
        self.assertIn("does not execute providers", doc)
        self.assertIn("advisory policy envelope", doc)

    def test_provider_architecture_points_to_live_session_model(self):
        doc = (ROOT / "docs" / "provider-architecture.md").read_text(encoding="utf-8")

        self.assertIn("Shared Room Event Stream", doc)
        self.assertIn("docs/live-session-room-model.md", doc)
        self.assertIn("live_session", doc)
        self.assertIn("codex_live_session", doc)
        self.assertIn("codex exec resume", doc)
        self.assertIn("--sandbox read-only", doc)
        self.assertIn("--ignore-rules", doc)
        self.assertIn("Codex CLI still owns the actual enforcement", doc)
        self.assertIn("not native Codex/Claude channel injection", doc)
        self.assertIn("Resident `terminal_session`", doc)
        self.assertIn("local PTY-backed slice", doc)
        self.assertIn("not Claude Code Channels, Antigravity native sessions, tmux ownership, or OS-level sandboxing", doc)
        self.assertIn("Resident `self_service`", doc)
        self.assertIn("director-led team examples", doc)
        self.assertIn("configs/director-led-team.example.json", doc)
        self.assertIn("configs/agents.director-led-team.example.json", doc)
        self.assertIn("configs/live-agents.director-led-team.self-service.example.json", doc)
        self.assertIn("display/model slots only", doc)
        self.assertIn("wait-next", doc)
        self.assertIn("scripts/my_self_service_agent.py", doc)
        self.assertIn("Local stdio MCP is an adapter over the same room contract", doc)
        self.assertIn("assemble mcp serve --profile participant", doc)
        self.assertIn("read_since", doc)
        self.assertIn("read_transcript", doc)
        self.assertIn("Host-control tools stay a later design", doc)
        self.assertIn("memory/profile capsule gate report", doc)
        self.assertIn("assemble memory-capsule gate", doc)
        self.assertIn("advisory", doc)
        self.assertIn("SandboxLauncher", doc)
        self.assertIn("NoSandboxLauncher", doc)
        self.assertIn("sandbox_enforcement", doc)
        self.assertIn("codex_readonly", doc)
        self.assertIn("os_sandboxed", doc)

    def test_roadmap_mentions_room_event_log_and_live_session_adapter(self):
        doc = (ROOT / "docs" / "roadmap.md").read_text(encoding="utf-8")

        self.assertIn("Room Event Log", doc)
        self.assertIn("live_session adapter", doc)
        self.assertIn("Decision Gate", doc)
        self.assertIn("run bounded remaining template rounds", doc)
        self.assertIn("docs/product/V0_1_RELEASE_CHECKLIST.md", doc)

    def test_v0_1_release_checklist_records_completion_hardening_path(self):
        doc = (ROOT / "docs" / "product" / "V0_1_RELEASE_CHECKLIST.md").read_text(encoding="utf-8")
        normalized = " ".join(doc.split())
        operating_model = (ROOT / "docs" / "product" / "OPERATING_MODEL.md").read_text(encoding="utf-8")

        self.assertIn("AgentsAssemble v0.1 Release Checklist", doc)
        self.assertIn("Core Usable Flow", doc)
        self.assertIn("start the GUI room", doc)
        self.assertIn("invite or attach an approved agent", doc)
        self.assertIn("terminal self-service room tools", normalized)
        self.assertIn("run at least one official turn", doc)
        self.assertIn("Host-side PTY prompt injection does not satisfy this proof by itself", doc)
        self.assertIn("finalize without invented replies", doc)
        self.assertIn("read transcript, decision, shared memory, and return packet artifacts", doc)
        self.assertIn("Do not treat provider discovery as execution", doc)
        self.assertIn("Do not add the Trello/Jira roadmap board to the vanilla GUI", doc)
        self.assertIn("local stdio MCP room tooling", normalized)
        self.assertIn("local MCP participant tools", normalized)
        self.assertIn("The local MCP participant profile exposes only register, heartbeat, wait_next", normalized)
        self.assertIn("Host-control MCP remains out of scope", doc)
        self.assertIn("Verification Commands", doc)
        self.assertIn("python3 -m unittest tests.test_mcp_server -v", doc)
        self.assertIn("python3 -m unittest tests.test_gui_server tests.test_live_agent_smoke -v", doc)
        self.assertIn("Next Slice Queue", doc)
        self.assertIn("docs/product/V0_1_RELEASE_CHECKLIST.md", operating_model)

    def test_live_room_references_preserve_council_boundary(self):
        live_model = (ROOT / "docs" / "live-session-room-model.md").read_text(encoding="utf-8")
        provider_arch = (ROOT / "docs" / "provider-architecture.md").read_text(encoding="utf-8")
        roadmap = (ROOT / "docs" / "roadmap.md").read_text(encoding="utf-8")
        research_log = (ROOT / "docs" / "research-log.md").read_text(encoding="utf-8")
        combined = "\n".join([live_model, provider_arch, roadmap, research_log])

        self.assertIn("Stoops", combined)
        self.assertIn("Claude Code Channels", combined)
        self.assertIn("live room infrastructure", combined)
        self.assertIn("council workflow", combined)
        self.assertIn("free chat", combined)
        self.assertIn("official", combined)

    def test_live_agent_ops_documents_operator_smoke_path(self):
        doc = (ROOT / "docs" / "live-agent-ops.md").read_text(encoding="utf-8")

        self.assertIn("python3 -m agentsassemble.cli gui", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent run", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent run-group", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent session-smoke", doc)
        self.assertIn("session-smoke --json schema", doc)
        self.assertIn("finalization_status", doc)
        self.assertIn("artifact_paths", doc)
        self.assertIn("`초대 패킷` button", doc)
        self.assertIn("browser-generated register/wait-next packet", doc)
        self.assertIn("five resident transports when PTY terminal sessions are available", doc)
        self.assertIn("skips the `terminal_session` fake and reports `terminal_session_reason: pty_unavailable`", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes start", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes list", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes wait", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes stop", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes restart", doc)
        self.assertIn("--fail-on-attention", doc)
        self.assertIn("The `processes wait` command exits `0` only when the named group is ready", doc)
        self.assertIn("wrapped URL timeout", doc)
        self.assertIn("fake-alpha", doc)
        self.assertIn("fake-beta", doc)
        self.assertIn("configs/live-agents.example.json", doc)
        self.assertIn("configs/live-agents.provider-staging.example.json", doc)
        self.assertIn("contract example, not a native-ready bundle", doc)
        self.assertIn("Do not start it until the real-provider checklist below is satisfied.", doc)
        self.assertIn("auto-refresh in the GUI every 5 seconds", doc)
        self.assertIn("ignore volatile heartbeat age and monitor tick timestamps", doc)
        self.assertIn("Fake Live Session Smoke", doc)
        self.assertIn("Fake Terminal Session Smoke", doc)
        self.assertIn("--connection-kind live_session", doc)
        self.assertIn("--connection-kind terminal_session", doc)
        self.assertIn("JSONL", doc)
        self.assertIn("one local process", doc)
        self.assertIn("one-shot `live-agent delegate`", doc)
        self.assertIn("stops reading stdin", doc)
        self.assertIn("JSONL live-session subprocess starts in its own process group", doc)
        self.assertIn("timing out while writing a blocked request", doc)
        self.assertIn("claude", doc)
        self.assertIn("antigravity", doc)
        self.assertIn("Gemini CLI is now legacy", doc)
        self.assertIn("curl -X POST", doc)
        self.assertIn("/api/live-agent-health", doc)
        self.assertIn("GUI `상주 실행` panel reads `/api/live-agent-health`", doc)
        self.assertIn("meeting-owned session readiness", doc)
        self.assertIn("binding-compatible rather than id-only", doc)
        self.assertIn("binding_provider_missing", doc)
        self.assertIn("connection_kind_mismatch", doc)
        self.assertIn("active/total durable session-runs", doc)
        self.assertIn("process monitor liveness evidence in `process_monitor`", doc)
        self.assertIn("sessions.items", doc)
        self.assertIn("shared meeting memory health evidence in `shared_memory`", doc)
        self.assertIn("official event, open-question, and action-item counts without official reply text", doc)
        self.assertIn("host-admission health evidence in `admission`", doc)
        self.assertIn("not part of overall health degradation", doc)
        self.assertIn("durable session-run retry evidence in `session_runs`", doc)
        self.assertIn("session-run monitor liveness evidence in `session_run_monitor`", doc)
        self.assertIn("session-run attention", doc)
        self.assertIn("Diagnostic durable session-runs stay excluded from health", doc)
        self.assertIn("meeting:duplicate_active_group", doc)
        self.assertIn("compact `session attention` reason", doc)
        self.assertIn("diagnostic smoke artifacts stay excluded", doc)
        self.assertIn("/api/live-agent-session-smoke", doc)
        self.assertIn("pre-restart, post-restart, post-recover, and optional same-session soak lobby reply counts", doc)
        self.assertIn("auto lobby reply before restart, after restart, and after recover", doc)
        self.assertIn("--lobby-probes", doc)
        self.assertIn("--soak-cycles", doc)
        self.assertIn("repeated auto lobby reply before restart, after restart, and after recover", doc)
        self.assertIn("same recovered diagnostic session alive for bounded soak cycles", doc)
        self.assertIn("two numeric session smoke soak controls", doc)
        self.assertIn("both `세션진단` and `점검` with `세션 포함` send the same soak controls", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent health", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent discover", doc)
        self.assertIn("It only checks whether known executables are on `PATH`", doc)
        self.assertIn("entry_status", doc)
        self.assertIn("entry_mode", doc)
        self.assertIn("admission_status", doc)
        self.assertIn("host_approved_binding", doc)
        self.assertIn("meeting_missing", doc)
        self.assertIn("provider_kind_mismatch", doc)
        self.assertIn("binding_provider_missing", doc)
        self.assertIn("conflicting registrations are still allowed", doc)
        self.assertIn("join_semantics", doc)
        self.assertIn("context_durability", doc)
        self.assertIn("evidence_basis", doc)
        self.assertIn("agent_id", doc)
        self.assertIn("terminal_pty_prompt_bridge", doc)
        self.assertIn("codex_exec_resume", doc)
        self.assertIn("self_service_room_loop", doc)
        self.assertIn("process_lifetime", doc)
        self.assertIn("provider_managed_resume", doc)
        self.assertIn("operator_action", doc)
        self.assertIn("requires_approval", doc)
        self.assertIn("safety_note", doc)
        self.assertIn("cursor-agent", doc)
        self.assertIn("Grok Build", doc)
        self.assertIn("Hermes CLI", doc)
        self.assertIn("openclaw", doc)
        self.assertIn("unsupported_terminal", doc)
        self.assertIn("PTY terminal sessions are unavailable", doc)
        self.assertIn("POST /api/live-agent-discovery", doc)
        self.assertIn("write_config", doc)
        self.assertIn("session_bundle.group_id", doc)
        self.assertIn("`세션번들` checkbox", doc)
        self.assertIn("safe `agent_id`", doc)
        self.assertIn("per-candidate exact approval checkboxes", doc)
        self.assertIn("before preflight", doc)
        self.assertIn("`discovery.run` operation details record safe exact approval evidence", doc)
        self.assertIn("approved_agent_ids", doc)
        self.assertIn("unmatched_approval_count", doc)
        self.assertIn("approved_agents", doc)
        self.assertIn("approved_commands", doc)
        self.assertIn("`자동입장` always requests the session bundle", doc)
        self.assertIn("`실사용 CLI 승인` checkbox", doc)
        self.assertIn("selected an exact candidate approval", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent auto-join", doc)
        self.assertIn("--approve-real-providers", doc)
        self.assertIn("--approve-agent", doc)
        self.assertIn("--approve-command", doc)
        self.assertIn("approval_status", doc)
        self.assertIn("excluded from the generated resident config and session bundle", doc)
        self.assertIn("approval_required", doc)
        self.assertIn("Approved real-provider auto-join also sends `probe_bound_agents: true`", doc)
        self.assertIn("a failed or timed-out reply probe leaves the returned session/run degraded", doc)
        self.assertIn("durable session-run ensure", doc)
        self.assertIn("posts to `/api/live-agent-session-runs/ensure`", doc)
        self.assertIn("The resulting `session_run` stays visible", doc)
        self.assertIn("Unlike `discover`, this is an explicit start/resume/restart/recover operation", doc)
        self.assertIn("full automatic completion path", doc)
        self.assertIn("shared_memory/rolling-summary.md", doc)
        self.assertIn("shared_memory/open-questions.md", doc)
        self.assertIn("shared_memory/action-items.md", doc)
        self.assertIn("shared_memory_official_event_count", doc)
        self.assertIn("shared_memory_last_event_id", doc)
        self.assertIn("shared_memory in `/api/live-agents/<agent_id>/room`", doc)
        self.assertIn("Shared meeting memory", doc)
        self.assertIn("python3 -m agentsassemble.cli memory-capsule gate", doc)
        self.assertIn("required capsule files", doc)
        self.assertIn("implementation, filesystem writes, git writes, pushes, secrets", doc)
        self.assertIn("the room read treats the official log as the authoritative source", doc)
        self.assertIn("matching metadata with untrusted body text", doc)
        self.assertIn("cached by the live event file state", doc)
        self.assertIn("Durable index or embedded meeting memory is used only when no usable current official live events exist", doc)
        self.assertIn("without rewriting the artifact files", doc)
        self.assertIn("wait-next event payloads include `room.shared_memory`", doc)
        self.assertIn("Read room.shared_memory as official-only background context", doc)
        self.assertIn("`mcp` block", doc)
        self.assertIn("python3 -m agentsassemble.cli mcp serve --profile participant", doc)
        self.assertIn("agent-owned room tools", doc)
        self.assertIn("does not start the provider CLI or grant durable provider approval", doc)
        self.assertIn("Action item:", doc)
        self.assertIn("Open question:", doc)
        self.assertIn("--include-legacy-gemini", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent preflight", doc)
        self.assertIn("Terminal Self-Service Room Tools", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent read-since", doc)
        self.assertIn("MCP `read_since`", doc)
        self.assertIn("read-since diff", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent wait-next", doc)
        self.assertIn('action: "official_turn"', doc)
        self.assertIn('action: "lobby"', doc)
        self.assertIn('action: "return_packet"', doc)
        self.assertIn("read_command", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent return-packet", doc)
        self.assertIn("GET /api/live-agents/<agent_id>/return-packet", doc)
        self.assertIn("targeted return-packet event", doc)
        self.assertIn("reprojects the relative return-packet path", doc)
        self.assertIn("current live-agent row's meeting", doc)
        self.assertIn("does not accept arbitrary artifact paths", doc)
        self.assertIn("does not heartbeat, acknowledge, post replies, append operations, or expose sibling packets", doc)
        self.assertIn("only while the packet is still pending for that agent", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent wait-room-event", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent wait-official-turn", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent official-reply", doc)
        self.assertIn("AGENTSASSEMBLE_WAIT_NEXT_COMMAND", doc)
        self.assertIn("AGENTSASSEMBLE_SAY_COMMAND_TEMPLATE", doc)

        self.assertIn("AGENTSASSEMBLE_OFFICIAL_REPLY_COMMAND_TEMPLATE", doc)
        self.assertIn("AGENTSASSEMBLE_HEARTBEAT_COMMAND_TEMPLATE", doc)
        self.assertIn("AGENTSASSEMBLE_LEAVE_COMMAND", doc)
        self.assertIn("`--last-error={last_error}` style argv tokens", doc)
        self.assertIn("live-agent leave --json", doc)
        self.assertIn("cursor-only heartbeat", doc)
        self.assertIn("advanced `last_observed_event_id` and `last_observed_live_event_id` cursor values", doc)
        self.assertIn("sends cursor-only `online` heartbeats for timeout observations", doc)
        self.assertIn("Parent liveness heartbeats refresh `last_seen_at` without downgrading", doc)
        self.assertIn("wait-turn-request", doc)
        self.assertIn("answer-turn", doc)
        self.assertIn("When the live cursor event is no longer in the bounded room snapshot", doc)
        self.assertIn("last_observed_live_event_id", doc)
        self.assertIn("reply_command", doc)
        self.assertIn("include the `--` option boundary before `<reply>`", doc)
        self.assertIn("bounded CLI polling surface", doc)
        self.assertIn("not Claude Code Channels", doc)
        self.assertIn("Resident runners support only `local_cli`, `live_session`, `terminal_session`, `remote_bridge`, and `self_service`", doc)
        self.assertIn("Registration-only kinds such as `manual` and `codex_resume`", doc)
        self.assertIn("does not send prompts, start resident sessions, call remote bridges, or execute model turns", doc)
        self.assertIn("resolvable command executable named `codex`", doc)
        self.assertIn("no extra pre-`exec` arguments", doc)
        self.assertIn("codex exec --sandbox read-only --ignore-rules resume --skip-git-repo-check --help", doc)
        self.assertIn("resolved Codex CLI accepts the resident safety flags", doc)
        self.assertIn("before any supervised process, resident registration, or worker thread is launched", doc)
        self.assertIn("configs/live-agents.codex-session.example.json", doc)
        self.assertIn("python3 -m agentsassemble.cli sessions invite", doc)
        self.assertIn("python3 -m agentsassemble.cli sessions live-agent-config", doc)
        self.assertIn("next_commands", doc)
        self.assertIn("next_commands.ensure_session", doc)
        self.assertIn("codex exec resume", doc)
        self.assertIn("codex_session.invite", doc)
        self.assertIn("failed invite attempts", doc)
        self.assertIn("--sandbox read-only", doc)
        self.assertIn("--ignore-rules", doc)
        self.assertIn("Codex CLI still owns the actual enforcement", doc)
        self.assertIn("not native Codex/Claude channel injection", doc)
        self.assertIn("general sandbox for arbitrary local CLI and remote bridge residents", doc)
        self.assertIn("python3 -m agentsassemble.cli providers health", doc)
        self.assertIn("redacts auth values, command arguments, local `config_path`, and raw loader detail", doc)
        self.assertIn("--probe bridge", doc)
        self.assertIn("--probe api", doc)
        self.assertIn("does not call Messages, generateContent, chat/completions, or any prompt-bearing endpoint", doc)
        self.assertIn("/agentsassemble/health", doc)
        self.assertIn("does not call `/agentsassemble/run`", doc)
        self.assertIn("does not execute Claude", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent smoke", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent official-round-smoke", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent doctor", doc)
        self.assertIn("--official-round-smoke", doc)
        self.assertIn("--session-smoke", doc)
        self.assertIn("official-turn smoke check inside the same readiness payload", doc)
        self.assertIn("full session smoke check", doc)
        self.assertIn("GUI `점검` can include the same official-turn smoke check", doc)
        self.assertIn("공식 포함", doc)
        self.assertIn("세션 포함", doc)
        self.assertIn("diagnostic official-round smoke meetings", doc)
        self.assertIn("do not appear in `/api/meetings` or `/api/meetings/latest`", doc)
        self.assertIn("--probe-agent", doc)
        self.assertIn("--probe-group", doc)
        self.assertIn("opt-in targeted resident probes", doc)
        self.assertIn("launch-time manifest", doc)
        self.assertIn("up to 10 targeted probe agents", doc)
        self.assertIn("/api/live-agent-preflight", doc)
        self.assertIn("/api/provider-health", doc)
        self.assertIn("/api/live-agent-smoke", doc)
        self.assertIn("/api/live-agent-official-round-smoke", doc)
        self.assertIn("/api/live-agent-readiness", doc)
        self.assertIn("does not execute provider commands", doc)
        self.assertIn("readiness", doc)
        self.assertIn("diagnostic", doc)
        self.assertIn("Legacy smoke artifacts", doc)
        self.assertIn("does not contaminate later health checks", doc)
        self.assertIn("진단", doc)
        self.assertIn("credential-free", doc)
        self.assertIn("smoke local_cli ok", doc)
        self.assertIn("smoke live_session ok", doc)
        self.assertIn("smoke remote_bridge ok", doc)
        self.assertIn("fake `remote_bridge`", doc)
        self.assertIn("official round smoke", doc)
        self.assertIn("공식 라운드 smoke", doc)
        self.assertIn("--fail-on-degraded", doc)
        self.assertIn("--json", doc)
        self.assertIn("Exit code contract", doc)
        self.assertIn("`1`: health reached the server but reported non-`ok` while `--fail-on-degraded` was set", doc)
        self.assertIn("degraded", doc)
        self.assertIn("read-only snapshot", doc)
        self.assertIn("/api/live-agent-processes/local-cli-group/restart", doc)
        self.assertIn("auto restart is off by default", doc)
        self.assertIn("max_restarts", doc)
        self.assertIn("restart_backoff_seconds", doc)
        self.assertIn("stale_restart_after_seconds", doc)
        self.assertIn("stale watchdog", doc)
        self.assertIn("stale_watchdog_stop_failed", doc)
        self.assertIn("positive restart budget", doc)
        self.assertIn("heartbeat_interval + poll_interval", doc)
        self.assertIn("--stale-restart-after-seconds", doc)
        self.assertIn("--live-agent-stale-restart-after-seconds", doc)
        self.assertIn("The process CLI uses exit code `0` for successful supervisor requests", doc)
        self.assertIn("live-agent processes stop-running", doc)
        self.assertIn("/api/live-agent-processes/stop-running", doc)
        self.assertIn("process.stop_running", doc)
        self.assertIn("does not attempt to signal historical `unknown`, `error`, or already `stopped` records", doc)
        self.assertIn("marks matching agents `offline` immediately", doc)
        self.assertIn("offline reconciliation summary", doc)
        self.assertIn("offline_agent_ids", doc)
        self.assertIn("does not touch agents currently attached to another meeting", doc)
        self.assertIn("another running or restarting group with the same meeting id still expects that agent", doc)
        self.assertIn("does not control arbitrary OS PIDs", doc)
        self.assertIn("resets the auto-restart counter", doc)
        self.assertIn("supervised `run-group` processes start in their own process group", doc)
        self.assertIn("ordinary child processes created by the resident group", doc)
        self.assertIn("interruptible subprocess runner", doc)
        self.assertIn("active local provider commands are terminated", doc)
        self.assertIn("provider command hits its timeout", doc)
        self.assertIn("Direct resident `SIGTERM`", doc)
        self.assertIn("A non-shutdown worker failure is isolated to that worker", doc)
        self.assertIn("sibling workers are not closed just because one worker failed", doc)
        self.assertIn("best-effort `error` heartbeat with a sanitized `last_error`", doc)
        self.assertIn("raw exception messages", doc)
        self.assertIn("compact exception category", doc)
        self.assertIn("instead of surfacing `KeyboardInterrupt`", doc)
        self.assertIn("own process group", doc)
        self.assertIn(".agentsassemble/live_agents.json", doc)
        self.assertIn(".agentsassemble/lobby.jsonl", doc)
        self.assertIn(".agentsassemble/live-agent-runs/processes.json", doc)
        self.assertIn("become `unknown` with their stale `pid` cleared", doc)
        self.assertIn("Delegate provider subprocess stdout/stderr is captured by the runner", doc)
        self.assertIn("agents manifest", doc)
        self.assertIn("does not include command arguments, endpoint URLs, auth references", doc)
        self.assertIn(".agentsassemble/live-agent-runs/events.jsonl", doc)
        self.assertIn("lifecycle event history", doc)
        self.assertIn("/api/live-agent-process-events", doc)
        self.assertIn("assemble live-agent processes events", doc)
        self.assertIn("scan_limit", doc)
        self.assertIn("truncated", doc)
        self.assertIn("offline reconciliation summaries with expected/offline/skipped counts", doc)
        self.assertIn("default CLI process list and GUI process rows show the latest lifecycle offline summary", doc)
        self.assertIn("recovered_unknown", doc)
        self.assertIn("orphan running record marked unknown", doc)
        self.assertIn("targeted `session-readiness` and `check-session` responses", doc)
        self.assertIn("health process reasons and attention", doc)
        self.assertIn("recent_events", doc)
        self.assertIn("live-agent heartbeat", doc)
        self.assertIn("assemble live-agent list", doc)
        self.assertIn("live-agent list --fail-on-attention", doc)
        self.assertIn("live-agent list --require-host-approved", doc)
        self.assertIn("live-agent list --require-match", doc)
        self.assertIn("live-agent list --require-all-agents", doc)
        self.assertIn("meeting_id, agent_id, and status query filters", doc)
        self.assertIn("/api/live-agents?safe=1", doc)
        self.assertIn("safe roster projection", doc)
        self.assertIn("heartbeat_age_seconds", doc)
        self.assertIn("stale_after_seconds", doc)
        self.assertIn("last_observed_live_event_id", doc)
        self.assertIn("registration acknowledgement", doc)
        self.assertIn("live_agent.register", doc)
        self.assertIn("live-agent join-brief", doc)
        self.assertIn("POST /api/live-agent-join-brief", doc)
        self.assertIn("startup packet", doc)
        self.assertIn("agent_owned_entry_packet", doc)
        self.assertIn("entry_contract", doc)
        self.assertIn("Director-Led Agent-Owned Template", doc)
        self.assertIn("configs/director-led-team.example.json", doc)
        self.assertIn("configs/agents.director-led-team.example.json", doc)
        self.assertIn("configs/live-agents.director-led-team.self-service.example.json", doc)
        self.assertIn("hidden host prompt injection", doc)
        self.assertIn("local formatting only", doc)
        self.assertIn("execution_contract", doc)
        self.assertIn("context_durability", doc)
        self.assertIn("not_started_by_join_brief", doc)
        self.assertIn("commands.wait_next", doc)
        self.assertIn("commands.leave", doc)
        self.assertIn("live-agent leave", doc)
        self.assertIn("POST /api/live-agents/<agent_id>/leave", doc)
        self.assertIn("live_agent.leave", doc)
        self.assertIn("offline heartbeat", doc)
        self.assertIn('action: "observe_lobby"', doc)
        self.assertIn("non-reply `observe_lobby` actions", doc)
        self.assertIn("--source-event-id", doc)
        self.assertIn("live_agent_endpoint", doc)
        self.assertIn("official cursor", doc)
        self.assertIn("wrong-meeting", doc)
        self.assertIn("cursor-only observation heartbeat fails transiently", doc)
        self.assertIn("Slow resident replies keep sending `working` heartbeats", doc)
        self.assertIn("--status error", doc)
        self.assertIn("--last-error", doc)
        self.assertIn("--last-observed-live-event-id", doc)
        self.assertIn("persisted heartbeat acknowledgement", doc)
        self.assertIn("Live-agent presence error details redacted.", doc)
        self.assertIn("the final heartbeat can report `offline` while preserving `last_error`", doc)
        self.assertIn("reuse `last_observed_event_id`", doc)
        self.assertIn("skip visible official turn requests that already have a same-agent reply", doc)
        self.assertIn("does not resume old resident agents except pending auto-restart records", doc)
        self.assertIn("backend supervisor monitor", doc)
        self.assertIn("without an open browser", doc)
        self.assertIn("event: error", doc)
        self.assertIn("/api/meetings/<meeting_id>/events", doc)
        self.assertIn("ordinary JSON `404`", doc)
        self.assertIn("operations.jsonl", doc)
        self.assertIn("/api/live-agent-operations", doc)
        self.assertIn("assemble live-agent operations list", doc)
        self.assertIn("--scan-limit", doc)
        self.assertIn("filters are applied before the result limit", doc)
        self.assertIn("live-agent operations list --fail-on-attention", doc)
        self.assertIn("live-agent operations wait", doc)
        self.assertIn("global marker semantics remain unchanged", doc)
        self.assertIn("session-runs.json", doc)
        self.assertIn("/api/live-agent-session-runs/ensure", doc)
        self.assertIn("adds `상주보장` for the durable session-run path", doc)
        self.assertIn("/api/live-agent-session-runs?limit=20", doc)
        self.assertIn("retry failure count/backoff/next retry time", doc)
        self.assertIn("waiting for its next durable retry", doc)
        self.assertIn("It does not render saved config paths", doc)
        self.assertIn("assemble live-agent session-runs list", doc)
        self.assertIn("assemble live-agent session-runs retry-now", doc)
        self.assertIn("assemble live-agent session-runs pause", doc)
        self.assertIn("assemble live-agent session-runs resume", doc)
        self.assertIn("assemble live-agent session-runs stop", doc)
        self.assertIn("assemble live-agent session-runs wait", doc)
        self.assertIn("/api/live-agent-session-runs/<run_id>/retry-now", doc)
        self.assertIn("/api/live-agent-session-runs/retry-now", doc)
        self.assertIn("exact `run_id` always wins", doc)
        self.assertIn("/api/live-agent-session-runs/<run_id>/pause", doc)
        self.assertIn("/api/live-agent-session-runs/<run_id>/resume", doc)
        self.assertIn("/api/live-agent-session-runs/<run_id>/stop", doc)
        self.assertIn("/api/live-agent-session-runs/pause", doc)
        self.assertIn("/api/live-agent-session-runs/resume", doc)
        self.assertIn("/api/live-agent-session-runs/stop", doc)
        self.assertIn("does not sweep older matching runs", doc)
        self.assertIn("before pause/resume eligibility checks", doc)
        self.assertIn("session_run.retry_now", doc)
        self.assertIn("session_run.pause", doc)
        self.assertIn("session_run.resume", doc)
        self.assertIn("session_run.stop", doc)
        self.assertIn("clears any saved retry delay", doc)
        self.assertIn("durable session-run status gate", doc)
        self.assertIn("without the exact run id", doc)
        self.assertIn("latest matching meeting/group session-run", doc)
        self.assertIn("/api/live-agent-session-runs?limit=N&run_id=...", doc)
        self.assertIn("Add `--run-id` when an operator or handoff script already knows the exact durable run id", doc)
        self.assertIn("For scriptable durable-run gates, add `--fail-on-attention`", doc)
        self.assertIn("filters that exact session-run before applying the limit window", doc)
        self.assertIn("/api/live-agent-session-runs?limit=N&meeting_id=...&group_id=...", doc)
        self.assertIn("filters matching meeting/group session-runs before applying the limit window", doc)
        self.assertIn("include_readiness=1", doc)
        self.assertIn("historical durable intent; current readiness is a separate read-only overlay", doc)
        self.assertIn("ready waits require the current readiness overlay to be `ready`", doc)
        self.assertIn("lifecycle-owned session-run monitor", doc)
        self.assertIn("last_tick_at", doc)
        self.assertIn("last_error_type", doc)
        self.assertIn("conservative runtime interval", doc)
        self.assertIn("Successful post-ready checks preserve `probe_bound_agents` and `probe_timeout_seconds`", doc)
        self.assertIn("durable reply-proof intent", doc)
        self.assertIn("consume one-shot durable request fields for remaining rounds and finalization", doc)
        self.assertIn("Failed post-ready checks keep the run `degraded`", doc)
        self.assertIn("reconcile_failure_count", doc)
        self.assertIn("reconcile_backoff_seconds", doc)
        self.assertIn("next_reconcile_at", doc)
        self.assertIn("does not trigger a mutating ensure attempt on every monitor tick", doc)
        self.assertIn("stored `ready` session-run", doc)
        self.assertIn("current readiness overlay is degraded", doc)
        self.assertIn("Unsafe process or session owner ids", doc)
        self.assertIn("reason labels", doc)
        self.assertIn("agents.attention", doc)
        self.assertIn("nested keys", doc)
        self.assertIn("absolute or relative slash/backslash path-like", doc)
        self.assertIn("missing-process-group-id-2", doc)
        self.assertIn("reconcile_failures=2", doc)
        self.assertIn("reconcile_backoff=120s", doc)
        self.assertIn("retry backoff fields", doc)
        self.assertIn("shuts down before the process supervisor", doc)
        self.assertIn("Recent operation views read from the JSONL tail", doc)
        self.assertIn("prioritize high-signal liveness evidence", doc)
        self.assertIn("session-smoke soak cycle/reply counts", doc)
        self.assertIn("live-agent health --wait-ok", doc)
        self.assertIn("live-agent health --wait-session-ready", doc)
        self.assertIn("live-agent session-readiness", doc)
        self.assertIn("scripts/my_self_service_agent.py", doc)
        self.assertIn("reads `return_packet` actions through the returned `read_command` before running the `ack_command`", doc)
        self.assertIn("treats missing or failed return-packet reads as `error` heartbeats without acknowledging delivery", doc)
        self.assertIn("treats failed lobby and official reply commands as cursor-bearing `error` heartbeats", doc)
        self.assertIn("treats failed return-packet and observe-lobby ack commands as `error` heartbeats with the matching cursor", doc)
        self.assertIn("self_service_official_reply_count", doc)
        self.assertIn("--wait-ready", doc)
        self.assertIn("live-agent ensure-session", doc)
        self.assertIn("세션보장", doc)
        self.assertIn("session_ensure_action", doc)
        self.assertIn("/api/live-agent-sessions/readiness", doc)
        self.assertIn("/api/live-agent-sessions/ensure", doc)
        self.assertIn("processes wait-event", doc)
        self.assertIn("rescan lifecycle history once per group", doc)
        self.assertIn("does not include command arguments, endpoint URLs, auth references, prompts, log tails", doc)
        self.assertIn("--live-agent-config", doc)
        self.assertIn("GUI startup autostart is explicit", doc)
        self.assertIn("does not autostart `configs/live-agents.example.json` by default", doc)
        self.assertIn("Durable session-run records are restart intent, not stored provider approval", doc)
        self.assertIn("durable ensure API", doc)
        self.assertIn("persisted process-group config", doc)
        self.assertIn("treated as approval only when it is JSON/CLI true", doc)
        self.assertIn("--approve-real-providers", doc)
        self.assertIn("transient real-provider approval flags", doc)
        self.assertIn("agent_connection", doc)
        self.assertIn("manifest-aware connection evidence", doc)
        self.assertIn("connection attention", doc)
        self.assertIn("live-agent probe", doc)
        self.assertIn("/api/live-agents/<agent_id>/probe", doc)
        self.assertIn("does not directly invoke providers", doc)
        self.assertIn("source_event_id", doc)
        self.assertIn("live_agent_endpoint", doc)
        self.assertIn("bounded 1000-event recent lobby tail", doc)
        self.assertIn("Resident room snapshots use the same 1000-event lobby tail", doc)
        self.assertIn("capped at 60 seconds", doc)
        self.assertIn("/api/live-agents/<agent_id>/engagement", doc)
        self.assertIn("assemble live-agent engagement", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent engagement", doc)
        self.assertIn("--mode watch", doc)
        self.assertIn("Valid modes are `manual`, `mentioned`, `moderator_called`, `human_only`, `always`, and `watch`", doc)
        self.assertIn("engagement_mode_updated_at", doc)
        self.assertIn("does not refresh `last_seen_at`", doc)
        self.assertIn("processes recover", doc)
        self.assertIn("process.recover", doc)
        self.assertIn("recovered_from_status", doc)
        self.assertIn("lifecycle `recovered`", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent start-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent check-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent restart-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent recover-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent stop-session", doc)
        self.assertIn("/api/live-agent-sessions/start", doc)
        self.assertIn("/api/live-agent-sessions/ensure", doc)
        self.assertIn("/api/live-agent-sessions/check", doc)
        self.assertIn("/api/live-agent-sessions/restart", doc)
        self.assertIn("/api/live-agent-sessions/recover", doc)
        self.assertIn("/api/live-agent-sessions/stop", doc)
        self.assertIn("configs/agents.start-session.example.json", doc)
        self.assertIn("configs/live-agents.start-session.example.json", doc)
        self.assertIn("status: \"ready\"", doc)
        self.assertIn("status: \"starting\"", doc)
        self.assertIn("status: \"degraded\"", doc)
        self.assertIn("status: \"stopped\"", doc)
        self.assertIn("status: \"stopping\"", doc)
        self.assertIn("session.start", doc)
        self.assertIn("session.ensure", doc)
        self.assertIn("ensure_action", doc)
        self.assertIn("post-ready checks", doc)
        self.assertIn("the CLI still posts once to `/api/live-agent-sessions/ensure`", doc)
        self.assertIn("ready-session drift guard", doc)
        self.assertIn("process-owned meeting id", doc)
        self.assertIn("does not create a replacement meeting", doc)
        self.assertIn("post-stop process status", doc)
        self.assertIn("while preserving any `reply_probe` and `auto_rounds` evidence", doc)
        self.assertIn("session.recover", doc)
        self.assertIn("post-recover", doc)
        self.assertIn("post-restart and post-recover reply counts", doc)
        self.assertIn("session.check", doc)
        self.assertIn("session.restart", doc)
        self.assertIn("session.stop", doc)
        self.assertIn("stopped session-run count", doc)
        self.assertIn("`세션중지` marks matching active session-runs as stopped", doc)
        self.assertIn("stale online rows cannot prove restart readiness", doc)
        self.assertIn("preflights the persisted restart config and server", doc)
        self.assertIn("preflights the persisted recover config and server", doc)
        self.assertIn("duplicate manifest agent ids", doc)
        self.assertIn("agent_id:wrong_meeting", doc)
        self.assertIn("agent-x:extra_in_group", doc)
        self.assertIn("does not run official turns unless `--run-remaining-rounds`", doc)
        self.assertIn("run_remaining_rounds", doc)
        self.assertIn("auto_rounds", doc)
        self.assertIn("session_not_ready", doc)
        self.assertIn("--finalize-after-rounds", doc)
        self.assertIn("finalization", doc)
        self.assertIn("rounds_still_remaining", doc)
        self.assertIn("finalization_status", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent call", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/request", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/call", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/sequence", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/round", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/rounds", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent review-checkpoint", doc)
        self.assertIn("/api/meetings/<meeting_id>/review-checkpoints", doc)
        self.assertIn("GUI Lobby `상주 실행` panel exposes this same path as `리뷰요청`", doc)
        self.assertIn("review.checkpoint", doc)
        self.assertIn("review_checkpoints/<checkpoint_id>.md", doc)
        self.assertIn("review_checkpoints/<checkpoint_id>.json", doc)
        self.assertIn("review checkpoint artifacts are Archive/operator records", doc)
        self.assertIn("excluded from official transcripts, shared memory, decisions, return packets, and operation details", doc)
        self.assertIn("does not include prompt or reply content", doc)
        self.assertIn("--wait", doc)
        self.assertIn("call-sequence", doc)
        self.assertIn("call-round", doc)
        self.assertIn("call-remaining-rounds", doc)
        self.assertIn("--turns-file", doc)
        self.assertIn("--round-id", doc)
        self.assertIn("Lobby `상주 실행` panel", doc)
        self.assertIn("`라운드호출`", doc)
        self.assertIn("`남은라운드`", doc)
        self.assertIn("official_turn.sequence", doc)
        self.assertIn("official_turn.round", doc)
        self.assertIn("official_turn.rounds", doc)
        self.assertIn("stop_on_timeout", doc)
        self.assertIn("status: \"answered\"", doc)
        self.assertIn("status: \"timeout\"", doc)
        self.assertIn("/api/live-agents/<agent_id>/official-turn", doc)
        self.assertIn("last_observed_live_event_id", doc)
        self.assertIn("official_record: true", doc)
        self.assertIn("build_meeting_payload()", doc)
        self.assertIn("projects the Archive transcript artifact", doc)
        self.assertIn("Existing `transcript.md` files always win", doc)
        self.assertIn("runner", doc)
        self.assertIn("does not replay the backlog", doc)
        self.assertIn("persisted lobby or official cursor has fallen outside the bounded room tail", doc)
        self.assertIn("recover when that cursor has aged out of the bounded room tail", doc)
        self.assertIn("Return-packet projection is the narrow exception", doc)
        self.assertIn("prove the packet is no longer pending", doc)
        self.assertIn("not native Claude Code Channels", doc)
        self.assertIn("The `terminal_session` transport is a local PTY bridge", doc)
        self.assertIn("Fake CLI", doc)
        self.assertIn("approval", doc)

    def test_readme_documents_live_room_status_and_honest_limits(self):
        doc = (ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn("## Live Room Status", doc)
        self.assertIn("Safe fake resident session quickstart", doc)
        self.assertIn("Terminal 1", doc)
        self.assertIn("Terminal 2", doc)
        self.assertIn("--run-remaining-rounds", doc)
        self.assertIn("--finalize-after-rounds", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent stop-session", doc)
        self.assertIn("Experimental Codex live session quickstart", doc)
        self.assertIn("no-model fake Codex lifecycle regression", doc)
        self.assertIn("native Claude Code/Cursor/Antigravity/Grok/Hermes/OpenClaw integrations are not complete", doc)
        self.assertIn("non-Codex local CLI read-only is not a hard OS sandbox", doc)
        self.assertIn("SandboxLauncher", doc)
        self.assertIn("sandbox_enforcement", doc)

    def test_provider_live_session_matrix_records_current_provider_readiness(self):
        doc = (ROOT / "docs" / "provider-live-session-matrix.md").read_text(encoding="utf-8")
        evidence = (ROOT / "docs" / "cli-evidence-survey.md").read_text(encoding="utf-8")

        for provider in (
            "codex_live_session",
            "kiro_live_session",
            "claude_code",
            "cursor",
            "antigravity_cli",
            "grok_build_cli",
            "hermes_cli",
            "openclaw_cli",
            "local_cli",
            "remote_http_bridge",
            "memory_pack",
        ):
            self.assertIn(provider, doc)
        self.assertIn("codex_exec_resume", doc)
        self.assertIn("kiro_chat_resume", doc)
        self.assertIn("continuity-proof", doc)
        self.assertIn("continuity-proof-group", doc)
        self.assertIn("provider-managed", doc)
        self.assertIn("process-lifetime", doc)
        self.assertIn("stateless-prompt", doc)
        self.assertIn("advisory", doc)
        self.assertIn("codex_readonly", doc)
        self.assertIn("fake `codex` executable", doc)
        self.assertIn("real Codex smoke", doc)
        self.assertIn("configs/live-agents.provider-staging.example.json", doc)
        self.assertIn("Codex and Kiro are the only provider-specific resume residents", doc)
        self.assertIn("local_cli is a stateless delegate", doc)
        normalized_evidence = " ".join(evidence.split())
        self.assertIn("Grok is the only non-Codex/Kiro provider with a passing two-turn continuity probe", normalized_evidence)
        for provider in ("claude_code", "cursor", "antigravity_cli", "grok_build_cli", "hermes_cli", "openclaw_cli"):
            self.assertIn(provider, evidence)
        for provider in ("claude_code", "openclaw_cli"):
            self.assertIn("unverified", evidence)

    def test_cli_evidence_survey_records_contract_known_but_unproven_providers(self):
        survey = (ROOT / "docs" / "cli-evidence-survey.md").read_text(encoding="utf-8")
        matrix = (ROOT / "docs" / "provider-live-session-matrix.md").read_text(encoding="utf-8")
        combined = "\n".join([survey, matrix])
        normalized_survey = " ".join(survey.split())
        normalized_combined = " ".join(combined.split())

        self.assertIn("help and version output can identify a candidate session surface", normalized_survey)
        self.assertIn("only an approved two-turn continuity probe can prove", normalized_survey)
        self.assertIn("model-inference commands require explicit real-provider approval", normalized_survey)
        self.assertIn("`cursor-agent --version` returned `2026.05.24-dda726e`", survey)
        self.assertIn("`agy --version` returned `1.0.1`", survey)
        self.assertIn("`grok --version` returned `grok 0.2.2 (c9b7cdec23a)`", survey)
        self.assertIn("`grok agent --help` exposes `stdio`, `headless`, `serve`, and `leader` modes", survey)
        self.assertIn("`hermes chat --help` exposes `--query`, `--resume`, `--continue`", survey)
        self.assertIn("bounded `hermes version` invocation did not return before timeout", survey)
        self.assertIn("status/account inspection is not safe public evidence", normalized_combined.lower())
        self.assertIn("Approved explicit-chat-id and workspace-continue probes both failed", normalized_combined)
        self.assertIn("continuity-proven-limited", normalized_combined)
        self.assertIn("only an approved two-turn continuity probe can prove", normalized_combined)

    def test_cli_evidence_survey_records_real_probe_outcomes(self):
        survey = (ROOT / "docs" / "cli-evidence-survey.md").read_text(encoding="utf-8")
        matrix = (ROOT / "docs" / "provider-live-session-matrix.md").read_text(encoding="utf-8")
        combined = "\n".join([survey, matrix])
        normalized = " ".join(combined.split())

        self.assertIn("Real Continuity Probe Summary", survey)
        self.assertIn("failed this probe", survey)
        self.assertIn("passed limited continuity probe", survey)
        self.assertIn("JSON stdout `text`", survey)
        self.assertIn("first assistant `text` length was 5", survey)
        self.assertIn("turn 2 assistant `text` length was 4", survey)
        self.assertIn("full process output did contain prompt material in stderr", survey)
        self.assertIn("Future provider-specific `grok_live_session`/runner is justified by evidence", normalized)
        self.assertIn("grok_session_resume", normalized)
        self.assertIn("This still does not prove room admission", normalized)
        self.assertIn("do not add a `cursor_agent` resume runner from current evidence", normalized)
        self.assertIn("Do not add an Antigravity runner yet", survey)
        self.assertIn("Do not add a Hermes runner yet", survey)

    def test_no_tailscale_multi_host_docs_separate_native_client_from_bridge(self):
        design = (ROOT / "docs" / "no-tailscale-multi-host.md").read_text(encoding="utf-8")
        room_model = (ROOT / "docs" / "live-session-room-model.md").read_text(encoding="utf-8")
        provider_arch = (ROOT / "docs" / "provider-architecture.md").read_text(encoding="utf-8")

        combined = "\n".join([design, room_model, provider_arch])
        self.assertIn("LAN invite token mode", design)
        self.assertIn("native_remote_room_client", combined)
        self.assertIn("remote_http_bridge", combined)
        self.assertIn("does not solve NAT traversal", design)
        self.assertIn("HMAC-SHA256", design)
        self.assertIn("remote agent admission and identity proof", design)
        self.assertIn("relay", design)
        self.assertIn("WebRTC", design)
        self.assertIn("not start provider CLIs", design)

    def test_live_agent_ops_and_audit_note_record_report_continuation_slice(self):
        ops = (ROOT / "docs" / "live-agent-ops.md").read_text(encoding="utf-8")
        audit = (ROOT / "docs" / "superpowers" / "audits" / "2026-05-22-live-room-report-continuation.md").read_text(
            encoding="utf-8"
        )

        self.assertIn("Codex Live Session Quickstart", ops)
        self.assertIn("configs/codex-live-session.example.json", ops)
        self.assertIn("configs/live-agents.codex-session.example.json", ops)
        self.assertIn("moderator_called", ops)
        self.assertIn("session id continuity through restart", ops)
        self.assertIn("sessions invite <codex-session-id>", ops)
        self.assertNotIn("sessions invite 019e", ops)
        self.assertIn("Report source", audit)
        self.assertIn("What changed", audit)
        self.assertIn("fake Codex lifecycle regression", audit)
        self.assertIn("What remains incomplete", audit)


if __name__ == "__main__":
    unittest.main()
