import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class DocsArchitectureTests(unittest.TestCase):
    def test_live_session_room_model_documents_shared_room_semantics(self):
        doc = (ROOT / "docs" / "live-session-room-model.md").read_text(encoding="utf-8")

        self.assertIn("shared room event stream", doc)
        self.assertIn("Agents do not receive isolated interview prompts", doc)
        self.assertIn("human", doc)
        self.assertIn("local_cli delegate", doc)
        self.assertIn("live_session", doc)
        self.assertIn("partial prefix/suffix matches do not count as a call", doc)
        self.assertIn("Codex app", doc)
        self.assertIn("CLI", doc)
        self.assertIn("memory capsule", doc)
        self.assertIn("advisory policy envelope", doc)

    def test_provider_architecture_points_to_live_session_model(self):
        doc = (ROOT / "docs" / "provider-architecture.md").read_text(encoding="utf-8")

        self.assertIn("Shared Room Event Stream", doc)
        self.assertIn("docs/live-session-room-model.md", doc)
        self.assertIn("live_session", doc)
        self.assertIn("codex_live_session", doc)
        self.assertIn("codex exec resume", doc)
        self.assertIn("--sandbox read-only", doc)
        self.assertIn("--ignore-rules", doc)
        self.assertIn("Codex CLI still owns the actual enforcement", doc)
        self.assertIn("not native Codex/Claude channel injection", doc)
        self.assertIn("not native Codex/Claude channel injection, verified PTY persistence, OS-level sandboxing", doc)
        self.assertIn("advisory", doc)

    def test_roadmap_mentions_room_event_log_and_live_session_adapter(self):
        doc = (ROOT / "docs" / "roadmap.md").read_text(encoding="utf-8")

        self.assertIn("Room Event Log", doc)
        self.assertIn("live_session adapter", doc)
        self.assertIn("Decision Gate", doc)
        self.assertIn("run bounded remaining template rounds", doc)

    def test_live_room_references_preserve_council_boundary(self):
        live_model = (ROOT / "docs" / "live-session-room-model.md").read_text(encoding="utf-8")
        provider_arch = (ROOT / "docs" / "provider-architecture.md").read_text(encoding="utf-8")
        roadmap = (ROOT / "docs" / "roadmap.md").read_text(encoding="utf-8")
        research_log = (ROOT / "docs" / "research-log.md").read_text(encoding="utf-8")
        combined = "\n".join([live_model, provider_arch, roadmap, research_log])

        self.assertIn("Stoops", combined)
        self.assertIn("Claude Code Channels", combined)
        self.assertIn("live room infrastructure", combined)
        self.assertIn("council workflow", combined)
        self.assertIn("free chat", combined)
        self.assertIn("official", combined)

    def test_live_agent_ops_documents_operator_smoke_path(self):
        doc = (ROOT / "docs" / "live-agent-ops.md").read_text(encoding="utf-8")

        self.assertIn("python3 -m agentsassemble.cli gui", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent run", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent run-group", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent session-smoke", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes start", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes list", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes wait", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes stop", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent processes restart", doc)
        self.assertIn("--fail-on-attention", doc)
        self.assertIn("The `processes wait` command exits `0` only when the named group is ready", doc)
        self.assertIn("wrapped URL timeout", doc)
        self.assertIn("fake-alpha", doc)
        self.assertIn("fake-beta", doc)
        self.assertIn("configs/live-agents.example.json", doc)
        self.assertIn("Do not start it until the real-provider checklist below is satisfied.", doc)
        self.assertIn("auto-refresh in the GUI every 5 seconds", doc)
        self.assertIn("Fake Live Session Smoke", doc)
        self.assertIn("--connection-kind live_session", doc)
        self.assertIn("JSONL", doc)
        self.assertIn("one local process", doc)
        self.assertIn("one-shot `live-agent delegate`", doc)
        self.assertIn("stops reading stdin", doc)
        self.assertIn("JSONL live-session subprocess starts in its own process group", doc)
        self.assertIn("timing out while writing a blocked request", doc)
        self.assertIn("claude", doc)
        self.assertIn("gemini", doc)
        self.assertIn("curl -X POST", doc)
        self.assertIn("/api/live-agent-health", doc)
        self.assertIn("GUI `상주 실행` panel reads `/api/live-agent-health`", doc)
        self.assertIn("meeting-owned session readiness", doc)
        self.assertIn("sessions.items", doc)
        self.assertIn("meeting:duplicate_active_group", doc)
        self.assertIn("compact `session attention` reason", doc)
        self.assertIn("diagnostic smoke artifacts stay excluded", doc)
        self.assertIn("/api/live-agent-session-smoke", doc)
        self.assertIn("pre-restart, post-restart, post-recover, and optional same-session soak lobby reply counts", doc)
        self.assertIn("auto lobby reply before restart, after restart, and after recover", doc)
        self.assertIn("--lobby-probes", doc)
        self.assertIn("--soak-cycles", doc)
        self.assertIn("repeated auto lobby reply before restart, after restart, and after recover", doc)
        self.assertIn("same recovered diagnostic session alive for bounded soak cycles", doc)
        self.assertIn("two numeric session smoke soak controls", doc)
        self.assertIn("both `세션진단` and `점검` with `세션 포함` send the same soak controls", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent health", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent preflight", doc)
        self.assertIn("Resident runners support only `local_cli`, `live_session`, and `remote_bridge`", doc)
        self.assertIn("Registration-only kinds such as `manual` and `codex_resume`", doc)
        self.assertIn("does not send prompts, start resident sessions, call remote bridges, or execute model turns", doc)
        self.assertIn("resolvable command executable named `codex`", doc)
        self.assertIn("no extra pre-`exec` arguments", doc)
        self.assertIn("codex exec --sandbox read-only --ignore-rules resume --skip-git-repo-check --help", doc)
        self.assertIn("resolved Codex CLI accepts the resident safety flags", doc)
        self.assertIn("before any supervised process, resident registration, or worker thread is launched", doc)
        self.assertIn("configs/live-agents.codex-session.example.json", doc)
        self.assertIn("codex exec resume", doc)
        self.assertIn("codex_session.invite", doc)
        self.assertIn("--sandbox read-only", doc)
        self.assertIn("--ignore-rules", doc)
        self.assertIn("Codex CLI still owns the actual enforcement", doc)
        self.assertIn("not native Codex/Claude channel injection", doc)
        self.assertIn("general sandbox for arbitrary local CLI and remote bridge residents", doc)
        self.assertIn("python3 -m agentsassemble.cli providers health", doc)
        self.assertIn("--probe bridge", doc)
        self.assertIn("/agentsassemble/health", doc)
        self.assertIn("does not call `/agentsassemble/run`", doc)
        self.assertIn("does not execute Claude", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent smoke", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent official-round-smoke", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent doctor", doc)
        self.assertIn("--official-round-smoke", doc)
        self.assertIn("--session-smoke", doc)
        self.assertIn("official-turn smoke check inside the same readiness payload", doc)
        self.assertIn("full session smoke check", doc)
        self.assertIn("GUI `점검` can include the same official-turn smoke check", doc)
        self.assertIn("공식 포함", doc)
        self.assertIn("세션 포함", doc)
        self.assertIn("diagnostic official-round smoke meetings", doc)
        self.assertIn("do not appear in `/api/meetings` or `/api/meetings/latest`", doc)
        self.assertIn("--probe-agent", doc)
        self.assertIn("--probe-group", doc)
        self.assertIn("opt-in targeted resident probes", doc)
        self.assertIn("launch-time manifest", doc)
        self.assertIn("up to 10 targeted probe agents", doc)
        self.assertIn("/api/live-agent-preflight", doc)
        self.assertIn("/api/provider-health", doc)
        self.assertIn("/api/live-agent-smoke", doc)
        self.assertIn("/api/live-agent-official-round-smoke", doc)
        self.assertIn("/api/live-agent-readiness", doc)
        self.assertIn("does not execute provider commands", doc)
        self.assertIn("readiness", doc)
        self.assertIn("diagnostic", doc)
        self.assertIn("Legacy smoke artifacts", doc)
        self.assertIn("does not contaminate later health checks", doc)
        self.assertIn("진단", doc)
        self.assertIn("credential-free", doc)
        self.assertIn("smoke local_cli ok", doc)
        self.assertIn("smoke live_session ok", doc)
        self.assertIn("smoke remote_bridge ok", doc)
        self.assertIn("fake `remote_bridge`", doc)
        self.assertIn("official round smoke", doc)
        self.assertIn("공식 라운드 smoke", doc)
        self.assertIn("--fail-on-degraded", doc)
        self.assertIn("--json", doc)
        self.assertIn("Exit code contract", doc)
        self.assertIn("`1`: health reached the server but reported non-`ok` while `--fail-on-degraded` was set", doc)
        self.assertIn("degraded", doc)
        self.assertIn("read-only snapshot", doc)
        self.assertIn("/api/live-agent-processes/local-cli-group/restart", doc)
        self.assertIn("auto restart is off by default", doc)
        self.assertIn("max_restarts", doc)
        self.assertIn("restart_backoff_seconds", doc)
        self.assertIn("stale_restart_after_seconds", doc)
        self.assertIn("stale watchdog", doc)
        self.assertIn("stale_watchdog_stop_failed", doc)
        self.assertIn("positive restart budget", doc)
        self.assertIn("heartbeat_interval + poll_interval", doc)
        self.assertIn("--stale-restart-after-seconds", doc)
        self.assertIn("--live-agent-stale-restart-after-seconds", doc)
        self.assertIn("The process CLI uses exit code `0` for successful supervisor requests", doc)
        self.assertIn("live-agent processes stop-running", doc)
        self.assertIn("/api/live-agent-processes/stop-running", doc)
        self.assertIn("process.stop_running", doc)
        self.assertIn("does not attempt to signal historical `unknown`, `error`, or already `stopped` records", doc)
        self.assertIn("marks matching agents `offline` immediately", doc)
        self.assertIn("offline reconciliation summary", doc)
        self.assertIn("offline_agent_ids", doc)
        self.assertIn("does not touch agents currently attached to another meeting", doc)
        self.assertIn("another running or restarting group with the same meeting id still expects that agent", doc)
        self.assertIn("does not control arbitrary OS PIDs", doc)
        self.assertIn("resets the auto-restart counter", doc)
        self.assertIn("supervised `run-group` processes start in their own process group", doc)
        self.assertIn("ordinary child processes created by the resident group", doc)
        self.assertIn("interruptible subprocess runner", doc)
        self.assertIn("active local provider commands are terminated", doc)
        self.assertIn("provider command hits its timeout", doc)
        self.assertIn("own process group", doc)
        self.assertIn(".agentsassemble/live_agents.json", doc)
        self.assertIn(".agentsassemble/lobby.jsonl", doc)
        self.assertIn(".agentsassemble/live-agent-runs/processes.json", doc)
        self.assertIn("become `unknown` with their stale `pid` cleared", doc)
        self.assertIn("Delegate provider subprocess stdout/stderr is captured by the runner", doc)
        self.assertIn("agents manifest", doc)
        self.assertIn("does not include command arguments, endpoint URLs, auth references", doc)
        self.assertIn(".agentsassemble/live-agent-runs/events.jsonl", doc)
        self.assertIn("lifecycle event history", doc)
        self.assertIn("/api/live-agent-process-events", doc)
        self.assertIn("assemble live-agent processes events", doc)
        self.assertIn("scan_limit", doc)
        self.assertIn("truncated", doc)
        self.assertIn("offline reconciliation summaries with expected/offline/skipped counts", doc)
        self.assertIn("default CLI process list and GUI process rows show the latest lifecycle offline summary", doc)
        self.assertIn("recovered_unknown", doc)
        self.assertIn("orphan running record marked unknown", doc)
        self.assertIn("targeted `session-readiness` and `check-session` responses", doc)
        self.assertIn("health process reasons and attention", doc)
        self.assertIn("recent_events", doc)
        self.assertIn("live-agent heartbeat", doc)
        self.assertIn("heartbeat_age_seconds", doc)
        self.assertIn("stale_after_seconds", doc)
        self.assertIn("last_observed_live_event_id", doc)
        self.assertIn("registration acknowledgement", doc)
        self.assertIn("--source-event-id", doc)
        self.assertIn("live_agent_endpoint", doc)
        self.assertIn("official cursor", doc)
        self.assertIn("wrong-meeting", doc)
        self.assertIn("Slow resident replies keep sending `working` heartbeats", doc)
        self.assertIn("--status error", doc)
        self.assertIn("--last-error", doc)
        self.assertIn("--last-observed-live-event-id", doc)
        self.assertIn("persisted heartbeat acknowledgement", doc)
        self.assertIn("Live-agent presence error details redacted.", doc)
        self.assertIn("the final heartbeat can report `offline` while preserving `last_error`", doc)
        self.assertIn("reuse `last_observed_event_id`", doc)
        self.assertIn("skip visible official turn requests that already have a same-agent reply", doc)
        self.assertIn("does not resume old resident agents except pending auto-restart records", doc)
        self.assertIn("backend supervisor monitor", doc)
        self.assertIn("without an open browser", doc)
        self.assertIn("event: error", doc)
        self.assertIn("/api/meetings/<meeting_id>/events", doc)
        self.assertIn("ordinary JSON `404`", doc)
        self.assertIn("operations.jsonl", doc)
        self.assertIn("/api/live-agent-operations", doc)
        self.assertIn("assemble live-agent operations list", doc)
        self.assertIn("live-agent operations list --fail-on-attention", doc)
        self.assertIn("live-agent operations wait", doc)
        self.assertIn("Recent operation views read from the JSONL tail", doc)
        self.assertIn("prioritize high-signal liveness evidence", doc)
        self.assertIn("session-smoke soak cycle/reply counts", doc)
        self.assertIn("live-agent health --wait-ok", doc)
        self.assertIn("live-agent health --wait-session-ready", doc)
        self.assertIn("live-agent session-readiness", doc)
        self.assertIn("--wait-ready", doc)
        self.assertIn("live-agent ensure-session", doc)
        self.assertIn("세션보장", doc)
        self.assertIn("session_ensure_action", doc)
        self.assertIn("/api/live-agent-sessions/readiness", doc)
        self.assertIn("/api/live-agent-sessions/ensure", doc)
        self.assertIn("processes wait-event", doc)
        self.assertIn("rescan lifecycle history once per group", doc)
        self.assertIn("does not include command arguments, endpoint URLs, auth references, prompts, log tails", doc)
        self.assertIn("--live-agent-config", doc)
        self.assertIn("GUI startup autostart is explicit", doc)
        self.assertIn("does not autostart `configs/live-agents.example.json` by default", doc)
        self.assertIn("agent_connection", doc)
        self.assertIn("manifest-aware connection evidence", doc)
        self.assertIn("connection attention", doc)
        self.assertIn("live-agent probe", doc)
        self.assertIn("/api/live-agents/<agent_id>/probe", doc)
        self.assertIn("does not directly invoke providers", doc)
        self.assertIn("source_event_id", doc)
        self.assertIn("live_agent_endpoint", doc)
        self.assertIn("capped at 60 seconds", doc)
        self.assertIn("/api/live-agents/<agent_id>/engagement", doc)
        self.assertIn("assemble live-agent engagement", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent engagement", doc)
        self.assertIn("--mode watch", doc)
        self.assertIn("Valid modes are `manual`, `mentioned`, `moderator_called`, `human_only`, `always`, and `watch`", doc)
        self.assertIn("engagement_mode_updated_at", doc)
        self.assertIn("does not refresh `last_seen_at`", doc)
        self.assertIn("processes recover", doc)
        self.assertIn("process.recover", doc)
        self.assertIn("recovered_from_status", doc)
        self.assertIn("lifecycle `recovered`", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent start-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent check-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent restart-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent recover-session", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent stop-session", doc)
        self.assertIn("/api/live-agent-sessions/start", doc)
        self.assertIn("/api/live-agent-sessions/ensure", doc)
        self.assertIn("/api/live-agent-sessions/check", doc)
        self.assertIn("/api/live-agent-sessions/restart", doc)
        self.assertIn("/api/live-agent-sessions/recover", doc)
        self.assertIn("/api/live-agent-sessions/stop", doc)
        self.assertIn("configs/agents.start-session.example.json", doc)
        self.assertIn("configs/live-agents.start-session.example.json", doc)
        self.assertIn("status: \"ready\"", doc)
        self.assertIn("status: \"starting\"", doc)
        self.assertIn("status: \"degraded\"", doc)
        self.assertIn("status: \"stopped\"", doc)
        self.assertIn("status: \"stopping\"", doc)
        self.assertIn("session.start", doc)
        self.assertIn("session.ensure", doc)
        self.assertIn("ensure_action", doc)
        self.assertIn("post-ready checks", doc)
        self.assertIn("unless `--probe-bound-agents` or `--run-remaining-rounds` is requested", doc)
        self.assertIn("while preserving any `reply_probe` and `auto_rounds` evidence", doc)
        self.assertIn("session.recover", doc)
        self.assertIn("post-recover", doc)
        self.assertIn("post-restart and post-recover reply counts", doc)
        self.assertIn("session.check", doc)
        self.assertIn("session.restart", doc)
        self.assertIn("session.stop", doc)
        self.assertIn("stale online rows cannot prove restart readiness", doc)
        self.assertIn("preflights the persisted restart config and server", doc)
        self.assertIn("preflights the persisted recover config and server", doc)
        self.assertIn("duplicate manifest agent ids", doc)
        self.assertIn("agent_id:wrong_meeting", doc)
        self.assertIn("agent-x:extra_in_group", doc)
        self.assertIn("does not run official turns unless `--run-remaining-rounds`", doc)
        self.assertIn("run_remaining_rounds", doc)
        self.assertIn("auto_rounds", doc)
        self.assertIn("session_not_ready", doc)
        self.assertIn("python3 -m agentsassemble.cli live-agent call", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/request", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/call", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/sequence", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/round", doc)
        self.assertIn("/api/meetings/<meeting_id>/live-agent-turns/rounds", doc)
        self.assertIn("--wait", doc)
        self.assertIn("call-sequence", doc)
        self.assertIn("call-round", doc)
        self.assertIn("call-remaining-rounds", doc)
        self.assertIn("--turns-file", doc)
        self.assertIn("--round-id", doc)
        self.assertIn("Lobby `상주 실행` panel", doc)
        self.assertIn("`라운드호출`", doc)
        self.assertIn("`남은라운드`", doc)
        self.assertIn("official_turn.sequence", doc)
        self.assertIn("official_turn.round", doc)
        self.assertIn("official_turn.rounds", doc)
        self.assertIn("stop_on_timeout", doc)
        self.assertIn("status: \"answered\"", doc)
        self.assertIn("status: \"timeout\"", doc)
        self.assertIn("/api/live-agents/<agent_id>/official-turn", doc)
        self.assertIn("last_observed_live_event_id", doc)
        self.assertIn("official_record: true", doc)
        self.assertIn("build_meeting_payload()", doc)
        self.assertIn("projects the Archive transcript artifact", doc)
        self.assertIn("Existing `transcript.md` files always win", doc)
        self.assertIn("runner", doc)
        self.assertIn("does not replay the backlog", doc)
        self.assertIn("persisted lobby or official cursor has fallen outside the bounded room tail", doc)
        self.assertIn("recover when that cursor has aged out of the bounded room tail", doc)
        self.assertIn("not native Claude Code Channels", doc)
        self.assertIn("not a native Claude, Gemini, or Cursor PTY protocol", doc)
        self.assertIn("Fake CLI", doc)
        self.assertIn("approval", doc)


if __name__ == "__main__":
    unittest.main()
