import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATIC_DIR = ROOT / "agentsassemble" / "static"
PYPROJECT = ROOT / "pyproject.toml"


def static_js() -> str:
    return "\n".join(path.read_text() for path in sorted(STATIC_DIR.glob("*.js")))


def static_css() -> str:
    return "\n".join(path.read_text() for path in sorted(STATIC_DIR.glob("*.css")))


class StaticUiAssetTests(unittest.TestCase):
    def test_responsive_layout_hooks_are_present(self):
        css = static_css()

        self.assertIn("@media (max-width: 860px)", css)
        self.assertIn("@media (max-width: 560px)", css)
        self.assertIn("overflow-x: auto;", css)
        self.assertIn("contain: layout paint;", css)
        self.assertIn(":focus-visible", css)
        self.assertIn("width: min(28vw, 130px);", css)
        self.assertIn("#run-demo {\n    grid-column: 1 / -1;", css)

    def test_app_status_region_reports_demo_state(self):
        html = (STATIC_DIR / "index.html").read_text()
        script = static_js()
        css = static_css()

        self.assertIn('id="app-status"', html)
        self.assertIn('role="status"', html)
        self.assertIn('type="module"', html)
        self.assertIn('/static/base.css', html)
        self.assertIn('/static/responsive.css', html)
        self.assertIn("function showAppStatus", script)
        self.assertIn('showAppStatus("Mock Demo 실행 중"', script)
        self.assertIn('showAppStatus("Mock Demo 생성 완료"', script)
        self.assertIn(".app-status", css)

    def test_lobby_separates_stage_from_activity_feed(self):
        script = static_js()
        css = static_css()

        self.assertIn('class="lobby-summary"', script)
        self.assertIn('class="lobby-activity"', script)
        self.assertIn(".lobby-summary", css)
        self.assertIn(".lobby-activity", css)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr) auto;", css)
        self.assertIn("function renderApprovedBindings", script)
        self.assertIn('aria-label="승인된 본회의 에이전트"', script)
        self.assertIn(".approved-bindings", css)
        self.assertIn("function lobbyEventsSignature", script)
        self.assertIn("state.lobbySignature", script)
        self.assertIn("onlyIfChanged", script)
        self.assertIn("setLobbyEvents(payload.events || [])", script)
        self.assertIn("export function renderLobby(options = {})", script)
        self.assertIn("const previousScrollTop = previousFeed?.scrollTop || 0", script)
        self.assertIn("options.followLatest ?? isLobbyFeedNearBottom(lobby)", script)
        self.assertIn("function restoreLobbyFeedScroll", script)
        self.assertNotIn('class="lobby-inline-avatar"', script)
        self.assertIn("--lobby-avatar-size: clamp(28px", css)
        self.assertIn("padding: 10px clamp(22px", css)
        self.assertIn("scrollbar-gutter: stable;", css)
        self.assertIn("margin-right: 0;", css)
        self.assertIn(".lobby-event {\n  align-items: start;\n  color: #f0ede5;\n  contain: layout;", css)
        self.assertNotIn(".lobby-event {\n  align-items: start;\n  color: #f0ede5;\n  contain: layout paint;", css)
        self.assertIn("grid-template-columns: minmax(0, 1fr) var(--lobby-avatar-size);", css)
        self.assertIn(".lobby-mine .lobby-avatar,\n.lobby-my-agent .lobby-avatar {\n  grid-column: 2;", css)
        self.assertIn("height: var(--lobby-avatar-size);", css)
        self.assertIn("width: var(--lobby-avatar-size);", css)
        self.assertIn("white-space: nowrap;", css)
        self.assertIn("width: min(100%, 720px);", css)
        self.assertIn('document.querySelector("#lobby-message")?.focus()', script)
        self.assertIn('event.key !== "Enter" || event.isComposing', script)
        send_lobby = script[script.index("async function sendLobbyEvent") : script.index("async function sendLobbyRemote")]
        self.assertIn("const previousValue = messageInput?.value || \"\"", send_lobby)
        self.assertIn("if (messageInput && kind === \"message\") messageInput.value = \"\";", send_lobby)
        self.assertIn("renderLobby({ followLatest: shouldFollowLatest })", send_lobby)
        self.assertIn('activeInput && kind === "message" && activeInput.value === ""', send_lobby)
        self.assertIn("activeInput.value = previousValue", send_lobby)
        self.assertIn('id="lobby-ask-remote"', script)
        self.assertIn("/api/lobby/remote", script)
        self.assertIn("function hasRemoteLobbyBridge", script)
        self.assertIn("async function sendLobbyRemote", script)
        self.assertIn("function providerDisplayName", script)
        self.assertIn("function joinModeLabel", script)
        self.assertIn("function shortSessionId", script)
        self.assertIn('provider?.kind === "codex_live_session"', script)
        self.assertIn('return "Codex Live";', script)
        self.assertIn('return "이어받은 세션";', script)
        self.assertIn('title="${escapeHtml(binding.session_id)}"', script)

    def test_live_view_prioritizes_official_chat(self):
        script = static_js()
        css = static_css()

        self.assertIn('class="live-chat-header"', script)
        self.assertIn('class="live-overview-strip"', script)
        self.assertIn('class="message-list live-transcript live-chat-feed"', script)
        self.assertIn("function renderOfficialRoster", script)
        self.assertIn(".live-chat-room", css)
        self.assertIn(".live-chat-feed", css)
        self.assertIn(".live-overview-strip", css)
        self.assertIn("width: fit-content;", css)
        self.assertIn("border-radius: 16px 16px 16px 5px;", css)
        self.assertIn("grid-template-columns: minmax(0, 1fr) minmax(280px, 320px);", css)
        self.assertIn("min-height: clamp(520px, calc(100vh - 236px), 760px);", css)
        self.assertIn("position: sticky;", css)
        self.assertIn("이 영역의 발언은 transcript.md와 decision.md의 근거가 됩니다.", script)
        self.assertIn("isLiveTranscriptNearBottom(live)", script)
        self.assertIn("scrollLiveTranscriptToLatest(live)", script)
        self.assertIn("payload.live_events", script)
        self.assertIn("function renderLiveEvent", script)
        self.assertIn("function renderDecisionGateCard", script)
        self.assertIn("Decision Gate", script)
        self.assertIn("decision_gate", script)
        self.assertIn("function connectRoomStreams", script)
        self.assertIn('new EventSource("/api/events/lobby")', script)
        self.assertIn('new EventSource("/api/events/side-chat")', script)
        self.assertIn('new EventSource(`/api/meetings/${encodeURIComponent(meetingId)}/events`)', script)
        self.assertIn("function applyLobbyStreamPayload", script)
        self.assertIn("function applySideChatStreamPayload", script)
        self.assertIn("function applyMeetingStreamPayload", script)
        self.assertIn("payload.meeting_payload", script)
        meeting_stream_handler = script[
            script.index("function applyMeetingStreamPayload") : script.index("function applyFullMeetingPayloadFromStream")
        ]
        self.assertLess(
            meeting_stream_handler.index("payload.meeting_payload?.meeting"),
            meeting_stream_handler.index("const events = payload?.events || []"),
        )
        self.assertIn("function applyFullMeetingPayloadFromStream", script)
        self.assertIn("function startPollingFallback", script)
        self.assertIn("function mergeEventById", script)
        self.assertIn("function mergeEventsById", script)
        self.assertIn('class="latest-jump"', script)
        self.assertIn("function renderSystemLine", script)
        self.assertIn("function renderResearchEvent", script)
        self.assertIn("function renderRetryBadge", script)
        self.assertIn("event.retry_status", script)
        self.assertIn("재시도 회복", script)
        self.assertIn("function confidenceLabel", script)
        self.assertIn("function userVisibleSummary", script)
        self.assertIn("function highlightImportant", script)
        self.assertIn("function meetingModeLabel", script)
        self.assertIn("function moderatorStateLabel", script)
        self.assertIn("function decisionReasonLabel", script)
        self.assertIn("자유채팅", script)
        self.assertIn("토론모드", script)
        self.assertIn("모더레이터 OFF", script)
        self.assertIn("사용자 판정 필요", script)
        self.assertIn("모더레이터가 꺼져 있어 사용자가 최종 판정을 내려야 합니다.", script)
        self.assertIn('if (item.kind === "room_chat") return renderRoomChatEvent(item);', script)
        self.assertIn("function renderRoomChatEvent", script)
        self.assertIn("room-log.md", script)
        self.assertIn("function splitLongSentence", script)
        self.assertIn("function splitOverlongText", script)
        self.assertIn("sentence.length <= 150", script)
        self.assertIn("index += 110", script)
        self.assertIn("Codex moderator synthesis did not return parseable JSON", script)
        self.assertIn(".message {\n  align-items: flex-start;\n  contain: layout;", css)
        self.assertNotIn(".message {\n  align-items: flex-start;\n  contain: layout paint;", css)
        self.assertIn(".latest-jump", css)
        self.assertIn(".system-line", css)
        self.assertIn(".research-card", css)
        self.assertIn(".message-body mark", css)
        self.assertIn("function payloadSignature", script)
        self.assertIn("return JSON.stringify(payload)", script)
        self.assertIn("signature === state.payloadSignature", script)
        self.assertIn("followLatest: options.followLatest", script)
        self.assertIn("render({ liveRefresh: true })", script)
        self.assertIn('aria-label="공식 토론 기록"', script)
        self.assertIn('aria-live="polite"', script)
        self.assertIn(".record-badge", css)
        self.assertIn("function providerLabel", script)
        self.assertIn("function agentLabel", script)
        self.assertIn("meeting read-only", script)
        self.assertIn("class=\"evidence-claims-table\"", script)
        self.assertIn("function renderClaimRow", script)
        self.assertIn("function shortUrl", script)
        self.assertIn("function liveStatusLabel", script)
        self.assertIn("function liveEventCounts", script)
        self.assertIn("function renderDecisionGateBoard", script)
        self.assertIn('isGame ? "게임 상태" : "결정 상태"', script)
        self.assertIn('if (meeting?.meeting_mode === "game") return "게임모드";', script)
        self.assertIn('if (meeting?.meeting_mode === "game") return "게임 채팅";', script)
        self.assertIn("const systemLiveEvents = isGame ? []", script)
        self.assertIn("결정 ${escapeHtml(decisionGateLabel(gate.status))}", script)
        self.assertIn('if (status === "blocked") return "발언 실패";', script)
        self.assertNotIn("합의도", script)
        self.assertIn("게이트", script)
        self.assertIn("rerun_failed_debate_round", script)
        self.assertIn('message.status === "failed"', script)
        self.assertIn("공식 발언", script)
        self.assertIn("중단됨", script)
        self.assertIn("meetingStatusLabel", script)
        self.assertIn(".live-event-bubble", css)
        self.assertIn('class="side-chat-panel"', script)
        self.assertIn("/api/side-chat", script)
        self.assertIn("function renderSideChat", script)
        self.assertIn('class="side-chat-avatar"', script)
        self.assertIn("function sideChatSide", script)
        self.assertIn(".side-chat-panel", css)
        self.assertIn("--side-chat-avatar-size: clamp(24px", css)
        self.assertIn("grid-template-columns: minmax(0, 1fr) var(--side-chat-avatar-size);", css)
        self.assertIn(".side-mine .side-chat-avatar,\n.side-my-agent .side-chat-avatar {\n  grid-column: 2;", css)
        self.assertIn(".side-chat-bubble", css)
        self.assertIn('aria-label="비공식 채팅"', script)
        self.assertIn('root.querySelector("#side-chat-message")?.focus()', script)
        self.assertIn("async function sendSideChatMessage", script)
        send_side_chat = script[script.index("async function sendSideChatMessage") : script.index("function isSideChatFeedNearBottom")]
        self.assertLess(send_side_chat.index('input.value = "";'), send_side_chat.index('await fetchJson("/api/side-chat"'))
        self.assertIn('activeInput && activeInput.value === ""', send_side_chat)
        self.assertIn("activeInput.value = previousValue", send_side_chat)
        self.assertIn("const shouldFollowLatest = isSideChatFeedNearBottom(root)", send_side_chat)
        self.assertIn("refreshSideChatPanel({ followLatest: shouldFollowLatest })", send_side_chat)
        self.assertNotIn("renderLive(state.payload", send_side_chat)
        self.assertIn("function isSideChatFeedNearBottom", script)
        self.assertIn("function scrollSideChatToLatest", script)
        self.assertIn("function restoreSideChatScroll", script)
        self.assertIn("function updateSideChatOverview", script)
        self.assertIn('data-overview="side-chat"', script)
        self.assertIn("renderSystemEventStack(systemLiveEvents)", script)
        self.assertIn("공식 기록 제외", script)
        self.assertIn("sideChatDraft", script)
        self.assertIn("if (input && draft)", script)
        side_chat_loader = script[script.index("async function loadSideChat") : script.index("async function loadSideChatSafely")]
        self.assertIn("refreshSideChatFeed()", side_chat_loader)
        self.assertNotIn("renderLive", side_chat_loader)
        self.assertLess(script.index("renderSystemEventStack(systemLiveEvents)"), script.index('<main class="message-list live-transcript live-chat-feed"'))
        self.assertIn("max-height: clamp(300px, 34vh, 430px);", css)
        self.assertIn("min-height: clamp(220px, 28vh, 340px);", css)

    def test_board_cards_are_dynamic_and_scrollable(self):
        script = static_js()
        css = static_css()

        self.assertIn("(meeting.roles || []).map", script)
        self.assertIn('에이전트 ${(meeting.roles || []).length}', script)
        self.assertIn("grid-template-columns: repeat(auto-fit", css)
        self.assertIn("max-height: clamp(520px, 72vh, 780px);", css)

    def test_archive_surfaces_owner_and_document_type(self):
        script = static_js()
        css = static_css()

        self.assertIn("archiveOwnerLabel(state.archiveKey, payload)", script)
        self.assertIn("function archiveMeetingModeLabel", script)
        self.assertIn("function archiveModeratorStateLabel", script)
        self.assertIn("function compactArchiveEntries", script)
        self.assertIn('String(value || "").trim().length > 0', script)
        self.assertIn("function archiveOwnerLabel", script)
        self.assertIn("archiveKindLabel(key)", script)
        self.assertIn('if (key === "room-log.md") return "자유채팅";', script)
        self.assertIn('"room-log.md"', script)
        self.assertIn("function copyTextWithTextarea", script)
        self.assertIn("return copyTextWithTextarea(content)", script)
        self.assertIn("function buildArchiveManifest", script)
        self.assertIn("function buildEvidenceArchiveEntries", script)
        self.assertIn("function renderEvidenceArchiveMarkdown", script)
        self.assertIn("function renderEvidenceArchiveSection", script)
        self.assertIn("evidence/${roleId}.md", script)
        self.assertIn("근거 표", script)
        self.assertIn('class="archive-vault"', script)
        self.assertIn(".archive-vault", css)
        self.assertIn(".archive-stat", css)
        self.assertIn(".archive-list button strong", css)
        self.assertIn(".archive-list button span", css)
        self.assertIn("overflow-wrap: anywhere;", css)
        self.assertIn("word-break: keep-all;", css)
        self.assertIn(".evidence-claims-table", css)
        self.assertIn(".claim-table-wrap", css)

    def test_tabs_expose_semantic_state(self):
        html = (STATIC_DIR / "index.html").read_text()
        script = static_js()
        spec = (ROOT / "docs" / "gui-v0-spec.md").read_text()

        self.assertIn('role="tablist"', html)
        self.assertEqual(html.count('role="tab"'), 4)
        self.assertEqual(html.count('role="tabpanel"'), 4)
        self.assertIn("all four tabs", spec)
        self.assertIn("[로비] [실황] [작전판] [아카이브]", spec)
        self.assertIn('aria-selected="true"', html)
        self.assertEqual(html.count('tabindex="-1"'), 3)
        self.assertIn('tabindex="0"', html)
        self.assertIn('aria-controls="lobby"', html)
        self.assertIn('aria-labelledby="tab-lobby"', html)
        self.assertIn('tab.setAttribute("aria-selected"', script)
        self.assertIn("tab.tabIndex = isActive ? 0 : -1", script)
        self.assertIn("panel.hidden = !isActive", script)


if __name__ == "__main__":
    unittest.main()
