// Generated by scripts/generate_room_event_types.py. Do not edit.
import type { RoomAgentSession } from "../api/agentSessions";

export interface PublicRoomActor {
  participant_id?: string;
  participant_type?: string;
}

export interface PublicRoomAttachment {
  id: string;
  filename: string;
  content_type: string;
  size: number;
  is_image: boolean;
  url: string;
  download_url: string;
}

export interface PublicRoomGlobalAppearance {
  banner_preset: string;
  banner_image_url: string;
  icon_image_url: string;
  icon_label: string;
  invite_scope: string;
}

export interface PublicRoomGlobalChannel {
  id: string;
  name: string;
  type: string;
  position: number;
  created_at: string;
}

export interface PublicRoomGlobalSettings {
  label: string;
  topic: string;
  appearance: PublicRoomGlobalAppearance;
  conversation_mode: string;
  max_relay_turns: number;
  channels: PublicRoomGlobalChannel[];
}

export interface RoomEvent {
  v: number;
  id: string;
  seq: number;
  created_at: string;
  room_id: string;
  type: string;
  actor: PublicRoomActor;
  participant_id?: string;
  participant_type?: string;
  actor_id?: string;
  actor_type?: string;
  session_id?: string;
  turn_id?: string;
  source_event_id?: string;
  display_name?: string;
  avatar_image_url?: string;
  provider_kind?: string;
  content?: string;
  message_kind?: string;
  target_agent_id?: string;
  vote_id?: string;
  vote_question?: string;
  vote_options?: string[];
  vote_choice?: string;
  visibility?: string;
  phase?: string;
  status?: string;
  activity_kind?: string;
  category?: string;
  attachments?: PublicRoomAttachment[];
  latency?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  diagnostics?: Record<string, unknown>;
  agent_session?: RoomAgentSession;
  message_source?: string;
  relay_depth?: number;
  reason_code?: string;
  room_settings?: PublicRoomGlobalSettings;
}
