"""Stable public API for persona card import, storage, and prompt rendering."""

from agentsassemble.persona_cards.imports import (
    DEFAULT_PERSONA_ROOT,
    MAX_CARD_TEXT_CHUNK_BYTES,
    MAX_CHARX_TOTAL_ASSET_BYTES,
    MAX_DATA_URI_BYTES,
    PNG_SIGNATURE,
    RISU_ASSET_MARKER,
    RISU_EOF_MARKER,
    RISU_MODULE_MAGIC,
    RISU_MODULE_VERSION,
    decode_rpack,
    import_ccv3_persona,
    import_charx_persona,
    import_risum_persona,
    persona_card_from_ccv3,
    persona_card_from_risu_module,
    read_risum_module,
    read_risum_module_bytes,
)
from agentsassemble.persona_cards.models import (
    PersonaAsset,
    PersonaCard,
    PersonaImportReport,
    PersonaLoreEntry,
    PersonaLoreScanResult,
    PersonaPromptRender,
    RisuModulePayload,
)
from agentsassemble.persona_cards.rendering import (
    MAX_LORE_RECURSIVE_SCAN_DEPTH,
    active_lore_entries,
    persona_prompt_lines,
    render_persona_prompt,
    replace_persona_variables,
    scan_persona_lore,
)
from agentsassemble.persona_cards.storage import load_persona_card, save_persona_card


__all__ = [
    "DEFAULT_PERSONA_ROOT",
    "MAX_CARD_TEXT_CHUNK_BYTES",
    "MAX_CHARX_TOTAL_ASSET_BYTES",
    "MAX_DATA_URI_BYTES",
    "MAX_LORE_RECURSIVE_SCAN_DEPTH",
    "PNG_SIGNATURE",
    "PersonaAsset",
    "PersonaCard",
    "PersonaImportReport",
    "PersonaLoreEntry",
    "PersonaLoreScanResult",
    "PersonaPromptRender",
    "RISU_ASSET_MARKER",
    "RISU_EOF_MARKER",
    "RISU_MODULE_MAGIC",
    "RISU_MODULE_VERSION",
    "RisuModulePayload",
    "active_lore_entries",
    "decode_rpack",
    "import_ccv3_persona",
    "import_charx_persona",
    "import_risum_persona",
    "load_persona_card",
    "persona_card_from_ccv3",
    "persona_card_from_risu_module",
    "persona_prompt_lines",
    "read_risum_module",
    "read_risum_module_bytes",
    "render_persona_prompt",
    "replace_persona_variables",
    "save_persona_card",
    "scan_persona_lore",
]
