#!/usr/bin/env python3
"""Generate the frontend public room event types from the Python contract."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import NotRequired, get_args, get_origin, get_type_hints


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPOSITORY_ROOT / "frontend" / "src" / "types" / "generatedRoomEvent.ts"
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from agentsassemble.room.public_event_contract import (  # noqa: E402
    PublicRoomActor,
    PublicRoomAttachment,
    PublicRoomEvent,
)


TYPESCRIPT_NAME = {
    PublicRoomActor: "PublicRoomActor",
    PublicRoomAttachment: "PublicRoomAttachment",
    PublicRoomEvent: "RoomEvent",
}


def typescript_type(annotation: object) -> str:
    origin = get_origin(annotation)
    if origin is NotRequired:
        return typescript_type(get_args(annotation)[0])
    if annotation is str:
        return "string"
    if annotation is int:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is object:
        return "unknown"
    if annotation in TYPESCRIPT_NAME:
        return TYPESCRIPT_NAME[annotation]
    if origin is list:
        return f"{typescript_type(get_args(annotation)[0])}[]"
    if origin is dict:
        return "Record<string, unknown>"
    raise TypeError(f"Unsupported public room event annotation: {annotation!r}")


def render_interface(
    name: str,
    contract: type,
    *,
    required: set[str],
) -> list[str]:
    lines = [f"export interface {name} {{"]
    for field, annotation in get_type_hints(contract, include_extras=True).items():
        optional = "" if field in required else "?"
        field_type = (
            "RoomAgentSession"
            if name == "RoomEvent" and field == "agent_session"
            else typescript_type(annotation)
        )
        lines.append(f"  {field}{optional}: {field_type};")
    lines.append("}")
    return lines


def render() -> str:
    sections = [
        "// Generated by scripts/generate_room_event_types.py. Do not edit.",
        'import type { RoomAgentSession } from "../api/agentSessions";',
        "",
    ]
    contracts = (
        ("PublicRoomActor", PublicRoomActor),
        ("PublicRoomAttachment", PublicRoomAttachment),
        ("RoomEvent", PublicRoomEvent),
    )
    for index, (name, contract) in enumerate(contracts):
        required = (
            {
                field
                for field, annotation in get_type_hints(
                    contract,
                    include_extras=True,
                ).items()
                if get_origin(annotation) is not NotRequired
            }
            if contract.__total__
            else set()
        )
        sections.extend(
            render_interface(
                name,
                contract,
                required=required,
            )
        )
        if index < len(contracts) - 1:
            sections.append("")
    return "\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != generated:
            print(f"{OUTPUT_PATH.relative_to(REPOSITORY_ROOT)} is out of date.")
            return 1
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
